CREATE TABLE EventData(
  Id NVARCHAR(40) PRIMARY KEY,
  Reference NVARCHAR(50),
  BatchId NVARCHAR(50),
  CarrierParcelStatusDescription NVARCHAR(150),
  CarrierParcelStatusId INT,
  CmsDescription NVARCHAR(150),
  CmsId INT,
  CmsParcelStatusDescription NVARCHAR(150),
  CmsParcelStatusId INT,
  SourceCountry NVARCHAR(50),
  ParcelId INT,
  ConsignmentId NVARCHAR(50),
  StatusAchievedDateTime NVARCHAR(50),
  CmsNotifiedDateTime NVARCHAR(50),
  SystemNotifiedDateTime NVARCHAR(50),
  CreatedOn NVARCHAR(50),
  ConsignmentDirection NVARCHAR(150),
  CarrierId INT,
  CarrierName NVARCHAR(150),
  CarrierCode NVARCHAR(50),
  CarrierServiceId INT,
  CarrierServiceCode INT,
  CarrierServiceName NVARCHAR(150),
  ParcelStatusId INT,
  ParcelStatusDescription NVARCHAR(150)
)